id: PD4DACE6C
initial_creation_type: input
source_metadata:
  Title: Śabdabhedaprakāśaḥ
  Editor: Sriman Mahesvara
  Publisher: '-'
  Place of Publication: '-'
  Year: '-'
  शब्दभेदप्रकाशः:
    Text Version: Devanagari
    Input Personnel: Bibek Shakya
    Input Date: '2018'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Buddhist Studies
    Sponsor: University of the West
created_at: '2022-03-08T17:14:19.036815'
last_modified_at: '2022-03-08T17:14:19.036823'
